version: "3"

services:
  app:
    container_name: gradle
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "./projects"
        target: "/root/projects"

