version: "3"

services:
  app:
    container_name: gradle
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 8433:433
    volumes:
      - type: bind
        source: "./projects"
        target: "/root/projects"
      - type: bind
        source: "./nexus"
        target: "/opt/nexus"

