version: "3"

services:
  app:
    container_name: gradle
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 38081:8081
    volumes:
      - type: bind
        source: "./projects"
        target: "/root/projects"
      - type: bind
        source: "./sonatype-work"
        target: "/opt/nexus/sonatype-work"
