version: "3"

services:
  app:
    container_name: gradle
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: "./"
        target: "/root/projects"
  nexus:
    image: sonatype/nexus3
    ports:
      - 38081:8081
    volumes:
      - type: bind
        source: "./nexus-data"
        target: /nexus-data
