/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package javaSample

import spock.lang.Specification

class AppTest extends Specification {
    def "Appクラス.greetingメソッドの実行結果に対する試験を行います"() {
        setup: "Appクラスを生成し、"
        def app = new App()

        when: "greetingメソッドを実行したとき、"
        def result = app.greeting

        then: "Nullではなく、「Hello World!」という文字列が取得できること"
        result != null
        result == "Hello World!"
    }
    def "Appクラス.greetingメソッドの実行結果の型試験を行います"() {
        setup: "Appクラスを生成し、"
        def app = new App()

        when: "greetingメソッドを実行したとき、"
        def result = app.greeting

        then: "文字列型であること"
        result instanceof String
    }
}
